=== chunyangJ/structured-document/EXERCICE_2/exo2_DTD_ph2.dtd
<!ELEMENT bibliographie (livre|article)+>
<!ELEMENT livre (titre,auteur+,tome?,info_edition)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteur (nom)+>
<!ELEMENT nom (nom_famille, prenom+) >
<!ELEMENT nom_famille (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT tome EMPTY>
<!ELEMENT info_edition (editeur, lieu_edition, lieu_impression, ISBN)>
<!ELEMENT editeur (#PCDATA)>
<!ELEMENT lieu_edition (#PCDATA)>
<!ELEMENT lieu_impression (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>

<!ELEMENT article (titre, auteur+, ref_publication, avis_perso?)>
<!ELEMENT ref_publication (journal, numero_pages, numero_journal)>
<!ELEMENT journal (#PCDATA)>
<!ELEMENT numero_pages (#PCDATA)>
<!ELEMENT numero_journal (#PCDATA)>
<!ELEMENT avis_perso (#PCDATA)>
<!ATTLIST titre soustitre CDATA #IMPLIED>
<!ATTLIST tome nb_pages CDATA #REQUIRED 
               soustitre CDATA #IMPLIED>
<!ATTLIST titre soustitre CDATA #IMPLIED>
<!ATTLIST journal nom_journal CDATA "Feuille de Chou"
                  annee (2000|2001|2002|avant_2000|inconnue) "inconnue" >

=== chunyangJ/structured-document/EXERCICE_2/exo2_DTD_ph2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bibliographie SYSTEM "exo2_DTD_ph2.dtd">
<!--exo2_DTD_phase2-->
<bibliographie>
    <livre>
        <titre>Mémoires d’outre-tombe</titre>
        <auteur>
            <nom>
                <nom_famille>de Chateaubriand</nom_famille>
                <prenom>François-René</prenom>
            </nom>

        </auteur>
        <tome nb_pages="800" soustitre="Tome I"/>
        <info_edition>
            <editeur>Le Livre de Poche</editeur>
            <lieu_edition>Paris</lieu_edition>
            <lieu_impression>Sant Andreu de la Barca</lieu_impression>
            <ISBN>978-2253160793</ISBN>
        </info_edition>
    </livre>
    <article>
        <titre>Automatic labeling of semantic roles</titre>
        <auteur>
            <nom>
                <nom_famille>Gildea</nom_famille>
                <prenom>Daniel</prenom>
            </nom>
        </auteur>
        <auteur>
            <nom>
                <nom_famille>Jurafsky</nom_famille>
                <prenom>Daniel</prenom>
            </nom>
        </auteur>
        <ref_publication>
            <journal nom_journal="Computational linguistics" annee="2002"/>
            <numero_pages>245-288</numero_pages>
            <numero_journal>3</numero_journal>
        </ref_publication>
    </article>
</bibliographie>
